# Generated by Django 3.0.6 on 2020-05-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=13, unique=True)),
                ('data_nascimento', models.DateField()),
                ('profissoes', models.ManyToManyField(to='core.Profissao')),
            ],
        ),
    ]
