# Generated by Django 3.0.6 on 2020-05-20 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orgao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edital', models.CharField(max_length=10)),
                ('codigo_concurso', models.CharField(max_length=10, unique=True)),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Orgao')),
                ('profissoes', models.ManyToManyField(to='core.Profissao')),
            ],
        ),
    ]
